---
title: "Keel Evaluations"
author: "Cheyne Springbett"
date: "10/31/2022"
output: pdf_document
---

# Load libraries
```{r}
library(googlesheets4)
library(reshape2)

```


# Read in Sheets, combine keel dataset
```{r reading in google sheets}
sheetnames=sheet_names("https://docs.google.com/spreadsheets/d/1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA")
evalnames=grep("Keel Prominence", sheetnames, value=T)

keels=read_sheet("https://docs.google.com/spreadsheets/d/1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA", sheet=evalnames[1])

for (i in 2:length(evalnames)){
  keels=rbind(
    keels,
    read_sheet("https://docs.google.com/spreadsheets/d/1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA", sheet=evalnames[i])
  )
}
keels=data.frame(keels)
```

# Quantify Keel Evals
```{r}
code=c("VP", "P", "A","W", "M", "none")
value=c(4,3,2,1,0,NA)
lookup=data.frame(code,value)

for (i in 1:nrow(keels)){
  for (j in 2:6){
    keels[i,j]=lookup$value[lookup$code==keels[i,j]]
  }
}

```

# Convert to numeric
```{r}
keels$O1=as.numeric(keels$O1)
keels$O2=as.numeric(keels$O2)
keels$O3=as.numeric(keels$O3)
keels$O4=as.numeric(keels$O4)
keels$O5=as.numeric(keels$O5)
```


#Combine to get total means between observers
```{r}
dfmean=data.frame(c(
(aggregate(O1~Octopus_Tank,data=keels,FUN="mean",na.action=na.pass)),
(aggregate(O2~Octopus_Tank,data=keels,FUN="mean",na.action=na.pass)),
(aggregate(O3~Octopus_Tank,data=keels,FUN="mean",na.action=na.pass)),
(aggregate(O4~Octopus_Tank,data=keels,FUN="mean",na.action=na.pass)),
(aggregate(O5~Octopus_Tank,data=keels,FUN="mean",na.action=na.pass))
))

dfmean$Octopus_Tank.1<- NULL
dfmean$Octopus_Tank.2<- NULL
dfmean$Octopus_Tank.3<- NULL
dfmean$Octopus_Tank.4<- NULL

```

# Import specific dates of observations
```{r}
dates=grep("Keel Dates", sheetnames, value=T)
keeldate=read_sheet("https://docs.google.com/spreadsheets/d/1ckVjS4Jw9o_eg_l_TAwDFNp_evuu36sFHmXyUqT6YqA", sheet=dates[1])
```

# Convert to date format
```{r}
keeldate$In <- as.Date(keeldate$In, format="%m-%d")
keeldate$O1 <- as.Date(keeldate$O1, format="%m-%d")
keeldate$O2 <- as.Date(keeldate$O2, format="%m-%d")
keeldate$O3 <- as.Date(keeldate$O3, format="%m-%d")
keeldate$O4 <- as.Date(keeldate$O4, format="%m-%d")
keeldate$O5 <- as.Date(keeldate$O5, format="%m-%d")
```

# Get days between observations
```{r}
d1<-keeldate$O1-keeldate$In
d2<-keeldate$O2-keeldate$In
d3<-keeldate$O3-keeldate$In
d4<-keeldate$O4-keeldate$In
d5<-keeldate$O5-keeldate$In
```

# Create dataframe of days between observations 
```{r}
datedif <- matrix(c(d1,d2,d3,d4,d5), nrow = 5, byrow=TRUE)
colnames(datedif) = keeldate$Octopus_Tank
rownames(datedif) = c("O1","O2","O3","O4","O5")

datedif <- as.data.frame(datedif)
```

# Transcribe matching dataframe of mean keel evals

```{r}
dfmeancol <- matrix(c(dfmean$O1,dfmean$O2,dfmean$O3,dfmean$O4,dfmean$O5), ncol=10, byrow=TRUE)
colnames(dfmeancol)=dfmean$Octopus_Tank
rownames(dfmeancol) = c("O1","O2","O3","O4","O5")

dfmeancol <- as.data.frame(dfmeancol)                     
```

# Plot results
```{r}
plot(dfmeancol$Amanda_CS2~datedif$Amanda_CS2, type="l",
     main="Keel Loss",
     xlab="Days in Captivity",
     ylab="Keel Prominence",
     col="red",
     xlim=c(0,40),
     ylim=c(0,4)
     )
    

lines(dfmeancol$Brendon_CS4~datedif$Brendon_CS4, col="blue")
lines(dfmeancol$Jerry_CS2~datedif$Jerry_CS2, col="green")
lines(dfmeancol$Joe_CS1~datedif$Joe_CS1, col="orange")
lines(dfmeancol$Jordan_CS4~datedif$Jordan_CS4, col="purple")
lines(dfmeancol$Naddlie_CS1~datedif$Naddlie_CS1, col="lightblue")
lines(dfmeancol$Neola_CS5~datedif$Neola_CS5, col="black")
lines(dfmeancol$Oscar_CS3~datedif$Oscar_CS3, col="darkgreen")
lines(dfmeancol$Rian_CS5~datedif$Rian_CS5, col="gray")
lines(dfmeancol$Veronica_CS3~datedif$Veronica_CS3, col="coral")

legend("right", c("Amanda_CS2","Brendon_CS4","Jerry_CS2","Joe_CS1","Jordan_CS4","Naddlie_CS1",
   "Neola_CS5","Oscar_CS3","Rian_CS5","Veronica_CS3"),
   fill = c("blue","green","orange","purple","lightblue","black",
            "darkgreen","gray","coral"
   ))
```
```{r}
burrowers <- c("no","yes","yes","no","yes","no","yes","yes","no","yes")



```

```{r}
df3 <- df
df3$Burrowers <- burrowers
```

```{r}
keels.df=data.frame(
  stack(dfmeancol),
  measure=rep(rownames(dfmeancol),10),
  days=stack(datedif)$value,
  burrow="no"
)

colnames(keels.df)[1:2]=c("keel","octo")
keels.df=keels.df[,c(2,3,1,4,5)]

keels.df$burrow[keels.df$octo %in% colnames(dfmeancol)[burrowers=="yes"]]="yes"

```

